name: BLAS SYRK CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev libomp-dev gcc make
        
    - name: Build project
      run: |
        cd blas_syrk  # Заходим в папку с кодом
        make all
      
    - name: Run interface tests
      run: |
        cd blas_syrk
        make test
      
    - name: Run performance tests
      run: |
        cd blas_syrk
        make perf
